---
# vars file for ansible-role-proxmox
pve_base_dir: "/etc/pve"
pve_cluster_conf: "{{ pve_base_dir }}/corosync.conf"

# vault passwords:
root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37356330666331663239306131636530363031356666303539623339653164646338356137353738
          3565386566353961623964663738653861323431616332630a356639383463666565323063613538
          61386163393336633038313638646636336533366230353635346464326632393763326330333030
          6438613231636364640a663436333636666230626135663733656439636232633239386461653464
          32636438386163613432323565306462306266336163633061326538633131626165333464643436
          30626163313266326562346235653262393339393965313232376464326132363563626335363835
          39356166303533626136376632336133333864613333343333333333356463636239663439656134
          38623630386634343034326263353339323838643465396532623666643730616238323231646435
          61373761663965663033623731353361616161623831356663383434666636396130
