---
roles:
  # Install a role from Ansible Galaxy.
  # Install these roles using ansible-galaxy install -g -f -r roles/requirements-local.yml
  - name: waal70.ad_backup
    src: https://git.andrecatherine.net/waal70/ansible-role-ad_backup
    version: main
    scm: git
  - name: waal70.airgap
    src: https://git.andrecatherine.net/waal70/ansible-role-airgap
    version: main
    scm: git
  - name: waal70.ansible_control
    src: https://git.andrecatherine.net/waal70/ansible-role-ansible_control
    version: main
    scm: git
  - name: waal70.authentik
    src: https://git.andrecatherine.net/waal70/ansible-role-authentik
    version: main
    scm: git
  - name: waal70.backup
    src: https://git.andrecatherine.net/waal70/ansible-role-backup
    version: main
    scm: git
  - name: waal70.debian_common
    src: https://git.andrecatherine.net/waal70/ansible-role-debian_common
    version: main
    scm: git
  - name: waal70.debian_desktop
    src: https://git.andrecatherine.net/waal70/ansible-role-debian_desktop
    version: main
    scm: git
  - name: waal70.debian_omv
    src: https://git.andrecatherine.net/waal70/ansible-role-debian_omv
    version: main
    scm: git
  - name: waal70.dev_tools
    src: https://git.andrecatherine.net/waal70/ansible-role-dev_tools
    version: main
    scm: git
  - name: waal70.docker
    src: https://git.andrecatherine.net/waal70/ansible-role-docker
    version: main
    scm: git
  - name: waal70.eclipse
    src: https://git.andrecatherine.net/waal70/ansible-role-eclipse
    version: main
    scm: git
  - name: waal70.forgejo
    src: https://git.andrecatherine.net/waal70/ansible-role-forgejo
    version: main
    scm: git
  - name: waal70.gitea
    src: https://git.andrecatherine.net/waal70/ansible-role-gitea
    version: main
    scm: git
  - name: waal70.homepage
    src: https://git.andrecatherine.net/waal70/ansible-role-homepage
    version: main
    scm: git
  - name: waal70.immich
    src: https://git.andrecatherine.net/waal70/ansible-role-immich
    version: main
    scm: git
  - name: waal70.kiwix
    src: https://git.andrecatherine.net/waal70/ansible-role-kiwix
    version: main
    scm: git
  - name: waal70.log2ram
    src: https://git.andrecatherine.net/waal70/ansible-role-log2ram
    version: main
    scm: git
  - name: waal70.nfs
    src: https://git.andrecatherine.net/waal70/ansible-role-nfs
    version: main
    scm: git
  - name: waal70.nginx_pm
    src: https://git.andrecatherine.net/waal70/ansible-role-nginx_pm
    version: main
    scm: git
  - name: waal70.no_journal
    src: https://git.andrecatherine.net/waal70/ansible-role-no_journal
    version: main
    scm: git
  - name: waal70.paperless_ngx
    src: https://git.andrecatherine.net/waal70/ansible-role-paperless_ngx
    version: main
    scm: git
  - name: waal70.pi_common
    src: https://git.andrecatherine.net/waal70/ansible-role-pi_common
    version: main
    scm: git
  - name: waal70.pihole
    src: https://git.andrecatherine.net/waal70/ansible-role-pihole
    version: main
    scm: git
  - name: waal70.portainer
    src: https://git.andrecatherine.net/waal70/ansible-role-portainer
    version: main
    scm: git
  - name: waal70.powersave
    src: https://git.andrecatherine.net/waal70/ansible-role-powersave
    version: main
    scm: git
  - name: waal70.pve
    src: https://git.andrecatherine.net/waal70/ansible-role-pve
    version: main
    scm: git
  - name: waal70.pxe_prep
    src: https://git.andrecatherine.net/waal70/ansible-role-pxe_prep
    version: main
    scm: git
  - name: waal70.samba_ad_dc
    src: https://git.andrecatherine.net/waal70/ansible-role-samba_ad_dc
    version: main
    scm: git
  - name: waal70.ssh_host_key
    src: https://git.andrecatherine.net/waal70/ansible-role-ssh_host_key
    version: main
    scm: git
  - name: waal70.tftp
    src: https://git.andrecatherine.net/waal70/ansible-role-tftp
    version: main
    scm: git
  - name: waal70.unbound
    src: https://git.andrecatherine.net/waal70/ansible-role-unbound
    version: main
    scm: git
  - name: waal70.vaultwarden
    src: https://git.andrecatherine.net/waal70/ansible-role-vaultwarden
    version: main
    scm: git
  - name: waal70.virtualbox
    src: https://git.andrecatherine.net/waal70/ansible-role-virtualbox
    version: main
    scm: git
  - name: waal70.vscode
    src: https://git.andrecatherine.net/waal70/ansible-role-vscode
    version: main
    scm: git
  - name: waal70.yubikey
    src: https://git.andrecatherine.net/waal70/ansible-role-yubikey
    version: main
    scm: git
