---
# file: pve.yml
- name: Setup Proxmox VE servers based on standard Debian bookworm
  hosts: proxmox_nodes
  become: true
  roles:
    - role: waal70.pve
      when: pve_reset is undefined
    - role: waal70.pxe_prep
      when: pve_reset is defined # will become defined by adding -e "pve_reset=true" on command-line
