---
# file: ad-dc.yml
- name: Setup Samba based ad-dc over standard Debian bookworm
  hosts: activedirectory
  become: true
  roles:
    - waal70.samba_ad_dc
    - waal70.ad_backup
    - waal70.backup
  vars:
    backup_directories:
      - "/home/{{ ansible_user }}/samba_backups"
    backup_minute: "55"
