---
# file: 08-portainer-master.yml
- name: Setup main Portainer server. This is required when using a jumpserver
  hosts:
    - outpost
    - homeserver
    - testenvironment
  become: true
  # strategy: free # noqa: run-once[play]
  roles:
    - role: waal70.docker
    - role: waal70.portainer
