---
# file: 20-clients-common.yml
- name: Common tasks for client devices
  hosts:
    - dev-t440p
    - chromedev
    - airgap-01
  become: true
#  strategy: free # noqa: run-once[play]
  roles:
    - waal70.debian_common
  tasks:
    - name: Debug the hostname
      ansible.builtin.debug:
        msg: "Running on host {{ ansible_hostname }}"
