---
# file: 89-immich.yml
- name: Deploy newly developed roles to test environments
  hosts:
    - testenv
    - testenv2
  become: true
  roles:
    - waal70.forgejo
    # - { role: waal70.paperless_ngx, do_stack_update: false }
    # - waal70.homepage
    # - waal70.backup
