---
# group variables for all servers
stage: "development"
ansible_vault: "ansible-vault/{{ stage }}"
enable_journaling: true # Set to true to enable journaling, false to disable
enable_powersave: true
log2ram_size: 80M
log2ram_state: install # install, update, remove

sshd_config_file: /etc/ssh/sshd_config

interactive_user: awaal
interactive_home: /home/awaal
private_repo: "{{ lookup('ansible.builtin.env', 'HOME') | default('~') }}/ansible/home"
ansible_user: "{{ remote_user | default('ansible') }}"
install_key: "{{ private_repo }}/ssh-keys/{{ ansible_user }}/{{ ansible_user }}-key-install-only"
interactive_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63313964383637363938636535653265393836363230363331633064666333336430366362303666
      3731343066303263366339353066373331616435336561610a306436613461346163653631616566
      65613439353434376235646435343031363730643834303035366232336431636630643038666234
      3139646665663931310a623835346338353461653633373831366139643234316263653762363261
      64323464613435393333626563626333626538626430623939303366663465663739656665623039
      30656361633138666662363464336162616361616164376264373335653161623531396433663063
      36616338323061303135653839393631393263333866616333636638303331326136623237396366
      31376230323333396339343431616663326466333965633539623134323931373039626364313235
      65333630373935633064356233386438646435323630626465303964323836666265
